version: '3.8'

services:
  app:
    build: .
    container_name: auth_app
    ports:
      - "5000:5000"
    env_file:
      - .env.test
    environment:
      - FLASK_ENV=development
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - cache
    restart: always

  db:
    image: mysql:8.0
    container_name: auth_db
    env_file:
      - .env.test
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      # HOST:CONTAINER
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  cache:
    image: redis:alpine
    container_name: auth_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  db_data: