apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  DB_USER: cm9vdA==                # 'root' encoded
  DB_PASS: cm9vdHBhc3N3b3Jk        # 'rootpassword' encoded
  DB_NAME: YXV0aF9kYg==            # 'auth_db' encoded
  JWT_SECRET: ZnVuY3Rpb25hbF90ZXN0X3NlY3JldF9rZXk= # your key encoded