# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  # Values must be base64 encoded. 
  # Hint: echo -n 'password' | base64
  DB_PASS: cm9vdHBhc3N3b3Jk 
  JWT_SECRET: ZnVuY3Rpb25hbF90ZXN0X3NlY3JldF9rZXk=